DEFAULT_TIMEOUT = 10
GUARDRAILS_ENDPOINT_URL = "/api/v1/guardrails/guard"
DEFAULT_THRESHOLD = 0.7
PARENT_SPAN_NAME = "cx.guardrails.session"
GUARDRAIL_SPAN_PREFIX = "guardrails."
TEST_SPAN_NAME = GUARDRAIL_SPAN_PREFIX + "test"